# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9e88fc95fce7150bc8c44370ecef7facb0a2a4744330958dfd07040116abb0e547f197ab3006ed4ccd758871543dba338ed01fb5abf4ccc71765c600936ebf2

test:
  secret_key_base: baae850ac86e8aa5ac9c31cbe4ec6e31f023d3c4908aad67c0affeddb4c8235a8412a1a783c431ffe4fa859f4728b59ae7abf1d769c0277f76da2bcea789d94a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
